/* NEXA UI v3 · radar + plano + auditoria automática + reset total */
(()=>{
'use strict';
if(window.__NEXA_UI_V3__)return;window.__NEXA_UI_V3__=true;
const $=id=>document.getElementById(id),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function installCss(){if($('nexaUiV3Style'))return;const s=document.createElement('style');s.id='nexaUiV3Style';s.textContent=`
.nexa-stage-view[data-stage="radar"].active{display:grid!important;grid-template-columns:minmax(0,1.55fr) minmax(290px,.55fr)!important;gap:14px!important;align-items:start!important}
.nexa-stage-view[data-stage="radar"]>.nexa-live-summary{display:none!important}
.nexa-stage-view[data-stage="radar"]>#realtimeRadarCard{display:block!important;grid-column:1!important;grid-row:1!important}
.nexa-stage-view[data-stage="radar"]>.card.rec-zone{display:block!important;position:sticky!important;top:72px!important;grid-column:2!important;grid-row:1!important;width:auto!important;height:auto!important;left:auto!important;overflow:visible!important;padding:18px!important;margin:0!important;border:1px solid var(--nexa-line)!important;border-radius:16px!important;background:var(--nexa-surface)!important;box-shadow:none!important}
.nexa-stage-view[data-stage="radar"] .rec-zone .wave-wrap,.nexa-stage-view[data-stage="radar"] .rec-zone .nexa-recording-tip{display:none!important}
.nexa-stage-view[data-stage="radar"] .rec-zone .rec-btn{width:58px!important;height:58px!important;margin:8px auto!important}
.nexa-stage-view[data-stage="radar"] .rec-zone .timer{font-size:42px!important;line-height:1!important;margin:10px 0!important}
.nexa-stage-view[data-stage="radar"] .rec-zone .nexa-rec-local-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;margin-top:14px!important}
.nexa-stage-view[data-stage="radar"] .rec-zone .nexa-rec-local-actions button{min-height:42px!important;border-radius:10px!important}
#nexaAuditAutoStatus{min-height:36px;padding:7px 10px;border:1px solid var(--nexa-line);border-radius:10px;background:var(--nexa-surface);color:var(--nexa-muted);font-weight:850;white-space:nowrap}
#nexaAuditAutoStatus.ok{color:var(--nexa-ok);border-color:color-mix(in srgb,var(--nexa-ok) 36%,var(--nexa-line));background:color-mix(in srgb,var(--nexa-ok) 7%,var(--nexa-surface))}
#nexaAuditAutoStatus.warn{color:var(--nexa-warn);border-color:color-mix(in srgb,var(--nexa-warn) 36%,var(--nexa-line))}
.nexa-radar-answered{display:grid;grid-template-columns:21px 1fr;gap:8px;align-items:start;padding:8px 10px;margin:5px 0;border:1px solid color-mix(in srgb,var(--nexa-ok) 35%,var(--nexa-line));border-radius:10px;background:color-mix(in srgb,var(--nexa-ok) 8%,var(--nexa-surface));color:var(--nexa-ok);font-size:11px;animation:nexaAnsweredOut 4.8s forwards}
.nexa-radar-answered b{width:20px;height:20px;border-radius:50%;display:grid;place-items:center;background:var(--nexa-ok);color:#fff}
@keyframes nexaAnsweredOut{0%,72%{opacity:1}100%{opacity:0}}
.nexa-plan-v3-tabs{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 12px}
.nexa-plan-v3-tabs button{border:1px solid var(--nexa-line);background:var(--nexa-surface);color:var(--nexa-muted);border-radius:999px;padding:8px 12px;font-weight:850;font-size:11px}
.nexa-plan-v3-tabs button.active{color:var(--nexa-brand);border-color:color-mix(in srgb,var(--nexa-brand) 35%,var(--nexa-line));background:color-mix(in srgb,var(--nexa-brand) 9%,var(--nexa-surface))}
.nexa-plan-v3-detail{display:none!important}.nexa-plan-v3-detail.active{display:block!important}
.nexa-stage-view[data-stage="plan"] .nexa-plan-overview{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:9px!important}
.nexa-stage-view[data-stage="plan"] .nexa-plan-action-card{min-height:76px!important}
@media(max-width:820px){.nexa-stage-view[data-stage="radar"].active{display:block!important}.nexa-stage-view[data-stage="radar"]>.card.rec-zone{position:relative!important;top:auto!important;margin-top:10px!important}.nexa-stage-view[data-stage="plan"] .nexa-plan-overview{grid-template-columns:1fr!important}}
`;document.head.appendChild(s)}
function placeRecorder(){const stage=q('.nexa-stage-view[data-stage="radar"]'),rec=q('.card.rec-zone');if(stage&&rec&&rec.parentElement!==stage)stage.appendChild(rec);q('.nexa-live-summary')?.setAttribute('aria-hidden','true')}

let prevQuestions=[];
function installRadarDynamics(){const host=$('radarQuestions');if(!host||host.dataset.nexaV3)return;host.dataset.nexaV3='1';const read=()=>qa('#radarQuestions .radar-question').map(x=>x.textContent.trim()).filter(Boolean);prevQuestions=read();new MutationObserver(()=>{const now=read();const gone=prevQuestions.filter(x=>!now.includes(x));if(gone.length){let box=$('nexaRadarAnsweredBox');if(!box){box=document.createElement('div');box.id='nexaRadarAnsweredBox';host.parentNode?.insertBefore(box,host.nextSibling)}gone.slice(0,2).forEach(t=>{const d=document.createElement('div');d.className='nexa-radar-answered';d.innerHTML=`<b>✓</b><span>${esc(t)}<small style="display:block;font-weight:800;margin-top:2px">Respondida / esclarecida</small></span>`;box.appendChild(d);setTimeout(()=>d.remove(),5000)})}prevQuestions=now}).observe(host,{childList:true,subtree:true})}

function installPlanTabs(){const block=$('clinicalPlanBlock');if(!block||$('nexaPlanV3Tabs'))return;const tabs=document.createElement('div');tabs.id='nexaPlanV3Tabs';tabs.className='nexa-plan-v3-tabs';tabs.innerHTML='<button class="active" data-v="overview">Visão geral</button><button data-v="exams">Exames</button><button data-v="rx">Tratamento</button><button data-v="guidance">Orientações</button><button data-v="conduct">Conduta</button>';block.insertBefore(tabs,block.firstChild);const exam=$('suggestedExams')?.closest('.plan-box')||$('suggestedExams')?.parentElement;const rx=$('rxOptions')?.closest('.plan-box')||$('suggestedPrescription')?.closest('.plan-box')||$('suggestedPrescription')?.parentElement;const guidance=q('.field[data-key="orientacoes_alta"]');const conduct=$('conductBlock');[exam,rx,guidance,conduct].filter(Boolean).forEach(x=>x.classList.add('nexa-plan-v3-detail'));const show=v=>{qa('#nexaPlanV3Tabs button').forEach(b=>b.classList.toggle('active',b.dataset.v===v));[exam,rx,guidance,conduct].filter(Boolean).forEach(x=>x.classList.remove('active'));({exams:exam,rx,guidance,conduct}[v])?.classList.add('active')};qa('#nexaPlanV3Tabs button').forEach(b=>b.onclick=()=>show(b.dataset.v));qa('.nexa-plan-action-card').forEach((b,i)=>b.addEventListener('click',()=>show(['exams','rx','guidance','conduct'][i]||'overview')))}

const A=window.__nexaAuditAuto={original:null,final:null,historyId:null,submitted:false,changedFields:[],capturedAt:null};
const fields=()=>{const o={};try{Object.entries(collect()||{}).forEach(([k,v])=>{if(typeof v==='string')o[k]=v})}catch{}return o};
const changed=(a,b)=>Object.keys({...a,...b}).filter(k=>String(a?.[k]||'')!==String(b?.[k]||''));
function auditStatus(text,cls=''){const b=$('nexaAuditAutoStatus');if(!b)return;b.className=cls;b.textContent=text}
function addAuditStatus(){const actions=q('.nexa-desktop-session-actions');if(!actions||$('nexaAuditAutoStatus'))return;const b=document.createElement('button');b.id='nexaAuditAutoStatus';b.type='button';b.textContent='Auditoria · automática';b.title='Captura automática: versão original preservada e versão final enviada ao encerrar o atendimento.';actions.insertBefore(b,actions.firstChild);b.onclick=()=>submitAuditSnapshot('manual_status')}
async function persistVersions(){if(!A.original)return;try{if(!A.historyId){if(!activeHistoryId&&typeof saveHistory==='function')await saveHistory();A.historyId=activeHistoryId||null}if(!A.historyId)return;A.final=fields();A.changedFields=changed(A.original,A.final);const meta={...(lastProcessedMeta||{}),audit_capture:{mode:'automatic',captured_at:A.capturedAt,original_fields:A.original,final_fields:A.final,changed_fields:A.changedFields,status:A.submitted?'submitted':'pending'}};await sb.from('consultation_history').update({processing_meta:meta,updated_at:new Date().toISOString()}).eq('id',A.historyId)}catch(e){console.warn('NEXA audit versions',e)}}
async function captureOriginal(){const f=fields();if(!Object.values(f).some(v=>v.trim()))return;A.original=f;A.final=f;A.submitted=false;A.changedFields=[];A.capturedAt=new Date().toISOString();auditStatus('Auditoria · original salvo');try{if(!activeHistoryId&&typeof saveHistory==='function')await saveHistory();A.historyId=activeHistoryId||null;await persistVersions()}catch(e){console.warn(e)}}
function coreContext(reason){let plan=null;try{plan=clinicalPlanCache.both||{exams:clinicalPlanCache.exams||null,prescription:clinicalPlanCache.prescription||null}}catch{};let hr={};try{hr={status:hypothesisReview.status||'pending',ai:hypothesisReview.ai||'',final:hypothesisReview.final||'',cid:hypothesisReview.cid||'',source:hypothesisReview.source||''}}catch{};let rr={chief_complaint:'',covered:[],missing:[],questions:[],alerts:[]};try{rr={chief_complaint:radarState?.chief_complaint||'',covered:radarState?.covered||[],missing:radarState?.missing||[],questions:radarState?.questions||[],alerts:radarState?.alerts||[]}}catch{};return{schema_version:'2',case_mode:typeof mode==='function'?mode():'upper',hypothesis_validation:hr,clinical_plan:plan,radar_learning:rr,provenance:{app_version:APP_CONFIG.appVersion,reviewed_documentation:false,radar_raw_transcript_saved:false,official_source:'automatic_final',audit_capture_mode:'automatic',original_version_preserved:true,changed_fields:A.changedFields,trigger:reason}}}
async function submitAuditSnapshot(reason='automatic_end',frozen=null){if(A.submitted||!A.original||!currentProf?.clinical_access)return;const final=frozen||fields();if(!Object.values(final).some(v=>v.trim()))return;A.final=final;A.changedFields=changed(A.original,final);auditStatus('Auditoria · enviando…');try{if(!A.historyId){if(!activeHistoryId&&typeof saveHistory==='function')await saveHistory();A.historyId=activeHistoryId||null}if(!A.historyId)throw new Error('Sem histórico da consulta');await persistVersions();const r=await fetch(SUPABASE_URL+APP_CONFIG.submitAuditPath,{method:'POST',headers:await sessionHeaders(),body:JSON.stringify({source_consultation_id:A.historyId,fields:final,core_context:coreContext(reason)}),keepalive:reason==='pagehide'});const d=await r.json().catch(()=>({}));if(!r.ok&&d.error!=='ALREADY_SUBMITTED')throw new Error(d.error||'Falha na auditoria');A.submitted=true;auditStatus('Auditoria ✓ salva','ok');await persistVersions()}catch(e){console.warn('NEXA auto audit',e);auditStatus('Auditoria ! pendente','warn')}}
function installAudit(){const p=$('processBtn');if(p&&!p.dataset.nexaAuditV3){p.dataset.nexaAuditV3='1';const old=p.onclick;p.onclick=async function(e){const r=old?await old.call(this,e):undefined;setTimeout(captureOriginal,120);return r}};const host=q('.nexa-stage-host')||document;let t=null;host.addEventListener('input',()=>{if(!A.original)return;clearTimeout(t);t=setTimeout(()=>persistVersions(),1800)});$('updateHistoryBtn')?.addEventListener('click',()=>setTimeout(persistVersions,120));window.addEventListener('pagehide',()=>{if(A.original&&!A.submitted)submitAuditSnapshot('pagehide',fields())})}

function resetInternals(){try{selectedConductOrder.length=0}catch{};try{examType=null}catch{};try{Object.keys(clinicalPlanCache||{}).forEach(k=>delete clinicalPlanCache[k])}catch{};try{resetRealtimeRadar?.()}catch{};qa('.nexa-stage-host input[type="checkbox"],.nexa-stage-host input[type="radio"]').forEach(x=>{if(x.id!=='useExamples')x.checked=false});qa('.conduct-template-check,.exam-sys-check,.rx-option input[type="checkbox"]').forEach(x=>x.checked=false);qa('.conduct-item.selected,.rx-option.selected,.exam-type-btn.active,.nexa-plan-action-card.active').forEach(x=>x.classList.remove('selected','active'));try{updateConductOrderBadges()}catch{};const es=$('examSystems');if(es)es.innerHTML='<div class="empty">Selecione um perfil para ver os sistemas.</div>';['suggestedExams','suggestedPrescription','rxMissingDataInput'].forEach(id=>{const e=$(id);if(e)e.value=''});['planGlobalAlerts','planScoreSuggestions'].forEach(id=>{const e=$(id);if(e)e.innerHTML=''});try{if(typeof initHypothesisReview==='function')initHypothesisReview('')}catch{};try{nexaClearPersistedSession()}catch{};A.original=A.final=null;A.historyId=null;A.submitted=false;A.changedFields=[];A.capturedAt=null;auditStatus('Auditoria · automática');setTimeout(()=>{try{loadConducts({silent:true})}catch{}},120)}
function installReset(){const reset=$('resetBtn');if(!reset||reset.dataset.nexaResetV3)return;reset.dataset.nexaResetV3='1';reset.addEventListener('click',()=>{const frozen=A.original?fields():null;if(frozen&&!A.submitted)submitAuditSnapshot('reset_new_consultation',frozen);setTimeout(()=>{const cleared=!qa('.nexa-stage-host textarea').some(x=>x.value.trim());if(cleared)resetInternals()},220)},true);$('nexaTopReset')?.addEventListener('click',()=>setTimeout(()=>{const cleared=!qa('.nexa-stage-host textarea').some(x=>x.value.trim());if(cleared)resetInternals()},260))}
function init(){installCss();placeRecorder();installRadarDynamics();installPlanTabs();addAuditStatus();installAudit();installReset();setTimeout(()=>{placeRecorder();installPlanTabs();addAuditStatus();installReset()},700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
