/* NEXA v18.10.1 — published clinical protocol library */
(()=>{
'use strict';
if(window.__NEXA_PROTOCOL_LIBRARY_V18_10_1__)return;
window.__NEXA_PROTOCOL_LIBRARY_V18_10_1__=true;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let timer=null,current=null,items=[];
function client(){return window.nexaClinicalSupabase18101||null}
async function api(payload){
 const c=client();if(!c?.functions?.invoke)throw new Error('Sessão inválida.');
 const {data,error}=await c.functions.invoke('protocol-library',{body:payload});
 if(error)throw new Error(error?.message||'Falha na Biblioteca Clínica.');
 return data||{}
}
function style(){if($('nexaProtocolLibraryStyle18101'))return;const s=document.createElement('style');s.id='nexaProtocolLibraryStyle18101';s.textContent=`
#nexaProtocolLibrary18101{position:fixed;z-index:78000;inset:0;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(4,17,28,.62);backdrop-filter:blur(5px)}
#nexaProtocolLibrary18101.open{display:flex}.npl-card{width:min(980px,96vw);max-height:92dvh;overflow:hidden;display:grid;grid-template-rows:auto auto minmax(0,1fr);border-radius:15px;border:1px solid var(--hair,#d8e1e7);background:var(--surface,#fff);color:var(--text,#11253c);box-shadow:0 24px 70px rgba(0,0,0,.2)}
.npl-head{display:flex;align-items:center;gap:10px;padding:14px 16px;border-bottom:1px solid var(--hair,#d8e1e7)}.npl-head h2{margin:0;font-size:18px}.npl-head span{font-size:10px;color:var(--muted,#708396)}.npl-spacer{flex:1}.npl-close{width:38px;height:38px;border:0;background:transparent;color:inherit;font-size:22px}
.npl-search{padding:12px 16px;border-bottom:1px solid var(--hair,#d8e1e7);display:grid;grid-template-columns:1fr auto;gap:8px}.npl-search input{height:42px;border:1px solid var(--hair,#d8e1e7);border-radius:9px;background:var(--surface2,#f7f9fa);color:inherit;padding:0 12px}.npl-search button,.npl-use{border:1px solid #1686a7;border-radius:9px;background:#1686a7;color:#fff;font-weight:850;padding:0 14px}
.npl-body{min-height:0;display:grid;grid-template-columns:340px minmax(0,1fr)}.npl-list{overflow:auto;border-right:1px solid var(--hair,#d8e1e7);padding:10px}.npl-item{width:100%;text-align:left;border:1px solid var(--hair,#d8e1e7);border-radius:10px;background:var(--surface2,#f7f9fa);color:inherit;padding:11px;margin-bottom:8px}.npl-item.active{border-color:#16a6a0;box-shadow:0 0 0 1px rgba(22,166,160,.15)}.npl-item b{display:block;font-size:12px}.npl-item small{display:block;color:var(--muted,#708396);margin-top:4px}
.npl-detail{overflow:auto;padding:16px}.npl-detail h3{margin:0 0 4px;font-size:19px}.npl-meta{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}.npl-pill{font-size:9px;padding:4px 7px;border:1px solid var(--hair,#d8e1e7);border-radius:999px}.npl-section{border-top:1px solid var(--hair,#d8e1e7);padding:12px 0}.npl-section h4{margin:0 0 6px;font-size:11px}.npl-section pre{white-space:pre-wrap;font:inherit;margin:0;color:inherit}.npl-rx{display:grid;gap:7px}.npl-rx>div{border:1px solid var(--hair,#d8e1e7);border-radius:8px;padding:9px;background:var(--surface2,#f7f9fa)}.npl-actions{display:flex;gap:8px;align-items:center;margin-top:14px}.npl-use{height:42px}.npl-use:disabled{opacity:.5}.npl-note{font-size:9.5px;color:var(--muted,#708396)}
@media(max-width:760px){#nexaProtocolLibrary18101{padding:0;align-items:flex-end}.npl-card{width:100%;max-height:95dvh;border-radius:16px 16px 0 0}.npl-body{grid-template-columns:1fr}.npl-list{max-height:240px;border-right:0;border-bottom:1px solid var(--hair,#d8e1e7)}.npl-detail{min-height:300px}}`;document.head.appendChild(s)}
function ensure(){if($('nexaProtocolLibrary18101'))return;style();const root=document.createElement('section');root.id='nexaProtocolLibrary18101';root.innerHTML=`<div class="npl-card"><div class="npl-head"><div><h2>Biblioteca Clínica</h2><span>Protocolos publicados · CID é mecanismo de busca, não decisão automática</span></div><div class="npl-spacer"></div><button class="npl-close" id="nplClose">×</button></div><div class="npl-search"><input id="nplSearch" placeholder="Buscar CID, doença, condição ou sinônimo"><button id="nplSearchBtn">Buscar</button></div><div class="npl-body"><div class="npl-list" id="nplList"></div><div class="npl-detail" id="nplDetail"><div class="npl-note">Pesquise uma condição para visualizar os protocolos publicados.</div></div></div></div>`;document.body.appendChild(root);$('nplClose').onclick=close;$('nplSearchBtn').onclick=()=>search($('nplSearch').value);$('nplSearch').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search($('nplSearch').value),220)});root.addEventListener('click',e=>{if(e.target===root)close();const b=e.target.closest('[data-npl-id]');if(b)select(b.dataset.nplId);if(e.target.closest('#nplUse'))useCurrent()})}
function renderList(){const host=$('nplList');host.innerHTML=items.map(x=>`<button class="npl-item ${current?.id===x.id?'active':''}" data-npl-id="${esc(x.id)}"><b>${esc(x.title)}</b><small>${esc((x.cid10||[]).join(', ')||'Sem CID associado')} · v${esc(x.version?.version_no||'')}</small></button>`).join('')||'<div class="npl-note">Nenhum protocolo publicado encontrado.</div>'}
function txt(v){return String(v||'').trim()}
function renderDetail(){const d=$('nplDetail');if(!current){d.innerHTML='<div class="npl-note">Selecione um protocolo.</div>';return}const v=current.version||{},rx=Array.isArray(v.prescription_items)?v.prescription_items:[],canUse=!!(window.currentProf?.clinical_access&&rx.length);d.innerHTML=`<h3>${esc(current.title)}</h3><div class="npl-meta">${(current.cid10||[]).map(x=>`<span class="npl-pill">${esc(x)}</span>`).join('')}<span class="npl-pill">Versão ${esc(v.version_no||'')}</span></div>${txt(v.clinical_scope)?`<div class="npl-section"><h4>Contexto / população</h4><pre>${esc(v.clinical_scope)}</pre></div>`:''}${txt(v.criteria_text)?`<div class="npl-section"><h4>Critérios</h4><pre>${esc(v.criteria_text)}</pre></div>`:''}${txt(v.required_data_text)?`<div class="npl-section"><h4>Dados necessários</h4><pre>${esc(v.required_data_text)}</pre></div>`:''}${txt(v.contraindications_text)?`<div class="npl-section"><h4>Alertas / contraindicações</h4><pre>${esc(v.contraindications_text)}</pre></div>`:''}<div class="npl-section"><h4>Prescrição modelo</h4>${rx.length?`<div class="npl-rx">${rx.map((m,i)=>`<div><b>${i+1}. ${esc([m.principio_ativo,m.apresentacao].filter(Boolean).join(' '))}</b><div>${esc(m.quantidade_total||'')}</div><div>${esc(m.manual_text||m.posologia||'')}</div></div>`).join('')}</div>`:(txt(v.prescription_text)?`<pre>${esc(v.prescription_text)}</pre>`:'<div class="npl-note">Sem modelo de prescrição cadastrado.</div>')}</div>${txt(v.guidance_text)?`<div class="npl-section"><h4>Orientações</h4><pre>${esc(v.guidance_text)}</pre></div>`:''}${txt(v.source_label)?`<div class="npl-section"><h4>Referência cadastrada</h4><pre>${esc(v.source_label)}${txt(v.source_page)?' · '+esc(v.source_page):''}</pre></div>`:''}<div class="npl-actions"><button id="nplUse" class="npl-use" ${canUse?'':'disabled'}>Usar na prescrição</button><span class="npl-note">${canUse?'Os itens serão inseridos no editor atual e ainda precisam ser revisados pelo médico.':rx.length?'Disponível apenas durante um atendimento clínico.':'Este protocolo não possui itens estruturados para inserção automática.'}</span></div>`}
function select(id){current=items.find(x=>x.id===id)||null;renderList();renderDetail()}
async function search(q=''){ensure();$('nplList').innerHTML='<div class="npl-note">Buscando…</div>';try{const d=await api({action:'search',q,limit:30});items=d.items||[];current=items[0]||null;renderList();renderDetail()}catch(e){$('nplList').innerHTML=`<div class="npl-note">${esc(e.message)}</div>`;$('nplDetail').innerHTML=''}}
function useCurrent(){if(!current)return;const n=window.nexaInsertProtocolPrescription18101?.(current,current.version);if(n>0){close();document.getElementById('rxOptions')?.scrollIntoView?.({behavior:'smooth',block:'start'})}}
function defaultQuery(){const cid=$('physicianCid')?.value?.trim();if(cid)return cid;const f=document.querySelector('.field[data-key="hipotese_diagnostica"] textarea')?.value?.trim();return f||''}
function open(query){ensure();$('nexaProtocolLibrary18101').classList.add('open');const q=query??defaultQuery();$('nplSearch').value=q;search(q)}
function close(){$('nexaProtocolLibrary18101')?.classList.remove('open')}
document.addEventListener('click',e=>{if(e.target?.closest?.('#searchProtocolRxBtn')){e.preventDefault();open()}},true);
window.nexaOpenProtocolLibrary18101=open;window.nexaProtocolLibrary18101={open,close,search,select,get current(){return current},get items(){return items}};
})();