/* NEXA v18.9.1 · functional auditor controls · 2026-09-05 */
(()=>{
'use strict';
if(window.__NEXA_AUDITOR_FUNCTIONAL_V18_9_1__)return;
window.__NEXA_AUDITOR_FUNCTIONAL_V18_9_1__=true;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,args){if(!window.sb)throw new Error('Sessão do NEXA Core indisponível.');const {data,error}=await window.sb.rpc(name,args);if(error)throw error;return data}
function auditorOpen(){return $('#nexaAuditExact')?.classList.contains('open')}
function closeReview(){$('#axReview')?.classList.remove('open')}
function returnMedical(){closeReview();$('#nexaAuditExact')?.classList.remove('open');document.documentElement.style.overflow='';document.body.style.overflow='';$('#nexaMobileDrawer')?.classList.remove('open');$('#nexaMobileDrawerOverlay')?.classList.remove('open');document.documentElement.classList.remove('nm-drawer-lock');const medical=$$('[data-mode="medical"],[data-work-mode="medical"],[data-mode="medico"],#n15Medico,#n9Medico').find(Boolean);try{medical?.click()}catch{}window.scrollTo({top:0,behavior:'instant'})}
function installStyle(){if($('#nexaAuditorFunctionalStyle'))return;const s=document.createElement('style');s.id='nexaAuditorFunctionalStyle';s.textContent=`
#axBackMedical{width:100%;height:38px;margin:10px 0 8px;border:1px solid var(--ax-line);border-radius:8px;background:var(--ax-panel);color:var(--ax-text);font-weight:900;text-align:left;padding:0 11px;cursor:pointer}
#axRefresh{height:32px;margin-left:8px;border:1px solid var(--ax-line);border-radius:7px;background:var(--ax-panel);color:var(--ax-text);font-weight:850;padding:0 10px;cursor:pointer}
.ax-nav button,.ax-filter,.ax-reviewbtn,.ax-actions button,.ax-decision button,.ax-back,.ax-rnav button,.ax-mobile-nav button,.ax-mobile-review-nav button{cursor:pointer}
.ax-actions button.ax-selected{outline:2px solid var(--ax-teal);outline-offset:1px;filter:brightness(1.15)}
.ax-section.ax-ok .ax-edit{opacity:.72}.ax-section.ax-problem{box-shadow:inset 3px 0 0 var(--ax-red)}
.ax-functional-page{display:grid;gap:10px}.ax-functional-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.ax-functional-item{background:var(--ax-panel);border:1px solid var(--ax-line);border-radius:9px;padding:14px}.ax-functional-item strong{font-size:22px;display:block;margin-top:5px}.ax-functional-actions{display:flex;gap:8px;flex-wrap:wrap}.ax-functional-actions button{height:34px;border:1px solid var(--ax-line);border-radius:7px;background:var(--ax-panel2);color:var(--ax-text);font-weight:800;padding:0 11px}
@media(max-width:900px){#axBackMedical{margin-top:4px}.ax-functional-grid{grid-template-columns:1fr 1fr}.ax-topbar #axRefresh{flex:0 0 auto}.ax-topbar .ax-search{min-width:0}}
`;document.head.appendChild(s)}
function ensureControls(){const side=$('.ax-side');if(side&&!$('#axBackMedical')){const b=document.createElement('button');b.id='axBackMedical';b.innerHTML='← Voltar ao Modo Médico';const mode=side.querySelector('.ax-mode');mode?.insertAdjacentElement('afterend',b)}const top=$('.ax-topbar');if(top&&!$('#axRefresh')){const b=document.createElement('button');b.id='axRefresh';b.textContent='↻ Atualizar';top.appendChild(b)}}
function nativeButtonByText(label){const rx=new RegExp(label,'i');return $$('button,a,[role="button"]').find(el=>!el.closest('#nexaAuditExact')&&!el.closest('#axReview')&&rx.test((el.textContent||'').trim()))}
function jumpNative(label){returnMedical();setTimeout(()=>{const el=nativeButtonByText(label);try{el?.click()}catch{}},50)}
async function renderStats(){const content=$('#axContent');if(!content)return;content.innerHTML='<div class="ax-card">Carregando estatísticas…</div>';try{const [qv,sv]=await Promise.all([rpc('get_audit_queue',{queue_status:null}),rpc('get_core_dataset_summary',{}).catch(()=>null)]);const rows=[...(qv||[])], c={pending:0,approved:0,corrected:0,discarded:0};rows.forEach(r=>{const s=['approved','corrected','discarded'].includes(r.status)?r.status:'pending';c[s]++});const done=c.approved+c.corrected,agree=done?Math.round(c.approved/done*100):0;content.innerHTML=`<div class="ax-functional-page"><div class="ax-head"><div><h1>Estatísticas</h1><p>Indicadores reais da fila de auditoria.</p></div></div><div class="ax-functional-grid"><div class="ax-functional-item">Pendentes<strong>${c.pending}</strong></div><div class="ax-functional-item">Aprovados<strong>${c.approved}</strong></div><div class="ax-functional-item">Corrigidos<strong>${c.corrected}</strong></div><div class="ax-functional-item">Descartados<strong>${c.discarded}</strong></div><div class="ax-functional-item">Concordância IA × auditor<strong>${agree}%</strong></div><div class="ax-functional-item">Total recebido<strong>${rows.length}</strong></div></div><div class="ax-card"><b>Resumo do NEXA Core</b><pre style="white-space:pre-wrap;color:var(--ax-muted);font-size:10px">${esc(JSON.stringify(Array.isArray(sv)?sv[0]:sv,null,2)||'Sem resumo adicional')}</pre></div><div class="ax-functional-actions"><button data-fn-panel>Voltar ao painel</button><button data-fn-refresh-stats>Atualizar estatísticas</button></div></div>`}catch(e){content.innerHTML=`<div class="ax-card"><b>Falha ao carregar estatísticas</b><p>${esc(e.message)}</p><button data-fn-refresh-stats>↻ Tentar novamente</button></div>`}}
async function renderLearning(){const content=$('#axContent');if(!content)return;content.innerHTML='<div class="ax-card">Carregando conjunto auditado…</div>';try{const sv=await rpc('get_core_dataset_summary',{}).catch(()=>null);content.innerHTML=`<div class="ax-functional-page"><div class="ax-head"><div><h1>Aprendizado</h1><p>Casos aprovados e corrigidos alimentam o conjunto auditado do NEXA Core.</p></div></div><div class="ax-card"><h3>Conjunto auditado</h3><pre style="white-space:pre-wrap;color:var(--ax-muted);font-size:10px">${esc(JSON.stringify(Array.isArray(sv)?sv[0]:sv,null,2)||'Nenhum resumo disponível.')}</pre></div><div class="ax-functional-actions"><button data-fn-audited>Ver casos auditados</button><button data-fn-panel>Voltar ao painel</button></div></div>`}catch(e){content.innerHTML=`<div class="ax-card">${esc(e.message)}</div>`}}
function setSidebarActive(view){$$('.ax-nav [data-ax-view]').forEach(b=>b.classList.toggle('active',b.dataset.axView===view));$$('.ax-mobile-nav [data-ax-view]').forEach(b=>b.classList.toggle('active',b.dataset.axView===view))}
function panel(){setSidebarActive('panel');window.nexaRefreshAuditExact?.()}
function queue(){setSidebarActive('queue');window.nexaRefreshAuditExact?.();setTimeout(()=>$('.ax-queue')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}
function audited(){window.nexaRefreshAuditExact?.();setTimeout(()=>{const b=$('.ax-filter[data-ax-filter="approved"]');b?.click();$('.ax-queue')?.scrollIntoView({behavior:'smooth',block:'start'})},120)}
function markReviewAction(btn,state){const sec=btn.closest('.ax-section'), ta=sec?.querySelector('[data-ax-field]');if(!sec)return;sec.classList.remove('ax-ok','ax-problem');sec.querySelectorAll('.ax-actions button').forEach(x=>x.classList.remove('ax-selected'));btn.classList.add('ax-selected');if(state==='ok'){sec.classList.add('ax-ok');if(ta)ta.readOnly=true}else if(state==='problem'){sec.classList.add('ax-problem');if(ta)ta.readOnly=false;ta?.focus()}else{if(ta)ta.readOnly=false;ta?.focus()}}
function navigateCase(dir){const buttons=$$('#nexaAuditExact [data-ax-open]');if(!buttons.length)return;const title=$('#axRTitle')?.textContent||'', prefix=(title.match(/#([A-Za-z0-9]+)/)||[])[1]?.toLowerCase()||'';let i=buttons.findIndex(b=>(b.dataset.axOpen||'').toLowerCase().startsWith(prefix));if(i<0)i=0;i=(i+dir+buttons.length)%buttons.length;closeReview();setTimeout(()=>buttons[i]?.click(),30)}
function bind(){document.addEventListener('click',e=>{if(!auditorOpen()&&!e.target.closest('#axReview'))return;const el=e.target.closest('button,a,[role="button"]');if(!el)return;if(el.id==='axBackMedical'){e.preventDefault();e.stopImmediatePropagation();returnMedical();return}if(el.id==='axRefresh'){e.preventDefault();window.nexaRefreshAuditExact?.();return}if(el.matches('.ax-nav [data-ax-view],.ax-mobile-nav [data-ax-view]')){const v=el.dataset.axView;if(v==='panel'){e.preventDefault();e.stopImmediatePropagation();panel();return}if(v==='queue'){e.preventDefault();e.stopImmediatePropagation();queue();return}if(v==='stats'){e.preventDefault();e.stopImmediatePropagation();setSidebarActive('stats');renderStats();return}if(v==='learn'){e.preventDefault();e.stopImmediatePropagation();setSidebarActive('learn');renderLearning();return}if(v==='protocols'){e.preventDefault();e.stopImmediatePropagation();jumpNative('Protocolos');return}if(v==='users'){e.preventDefault();e.stopImmediatePropagation();jumpNative('Usuários|Utilizadores|Médicos');return}if(v==='config'){e.preventDefault();e.stopImmediatePropagation();jumpNative('Configurações|Ajustes');return}}
if(el.classList.contains('ax-correctok')){e.preventDefault();markReviewAction(el,'ok');return}if(el.classList.contains('ax-correct')){e.preventDefault();markReviewAction(el,'edit');return}if(el.classList.contains('ax-problem')){e.preventDefault();markReviewAction(el,'problem');return}
if(el.matches('.ax-rnav button:nth-of-type(1)')){e.preventDefault();e.stopImmediatePropagation();navigateCase(-1);return}if(el.matches('.ax-rnav button:nth-of-type(2)')){e.preventDefault();e.stopImmediatePropagation();navigateCase(1);return}
if(el.matches('[data-fn-panel]')){e.preventDefault();panel();return}if(el.matches('[data-fn-refresh-stats]')){e.preventDefault();renderStats();return}if(el.matches('[data-fn-audited]')){e.preventDefault();audited();return}},true)}
function boot(){installStyle();ensureControls();bind();setTimeout(ensureControls,250);setTimeout(ensureControls,900)}
boot();
window.nexaReturnToMedicalMode=returnMedical;
window.nexaAuditorStats=renderStats;
window.nexaAuditorLearning=renderLearning;
})();