/* NEXA v18.9.2 · auditor panel + queue only · 2026-09-05 */
(()=>{
'use strict';
if(window.__NEXA_AUDITOR_PANEL_QUEUE_V18_9_2__)return;
window.__NEXA_AUDITOR_PANEL_QUEUE_V18_9_2__=true;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let rows=[],activeView='panel',filter='all',search='';
function client(){try{if(typeof sb!=='undefined'&&sb)return sb}catch{};return window.sb||null}
async function rpc(name,args){const c=client();if(!c)throw new Error('Sessão do NEXA Core indisponível.');const {data,error}=await c.rpc(name,args);if(error)throw error;return data}
function status(r){return ['approved','corrected','discarded'].includes(r?.status)?r.status:'pending'}
function statusText(s){return s==='approved'?'Aprovado':s==='corrected'?'Corrigido':s==='discarded'?'Descartado':'Pendente'}
function field(r,k){return r?.deidentified_fields?.[k]??''}
function mode(r){const m=String(r?.core_context?.case_mode||r?.deidentified_fields?.case_mode||'PS').toUpperCase();return m.startsWith('AMB')?'Amb.':'PS'}
function date(v){try{return new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return'—'}}
function coverage(r){const k=['queixa_principal','hda','antecedentes','comorbidades','exame_fisico','hipotese_diagnostica','conduta'];return Math.round(k.filter(x=>String(field(r,x)).trim()).length/k.length*100)}
function counts(){const c={pending:0,approved:0,corrected:0,discarded:0};rows.forEach(r=>c[status(r)]++);return c}
function filtered(){return rows.filter(r=>{if(filter!=='all'&&status(r)!==filter)return false;if(!search)return true;return (String(r.id)+' '+JSON.stringify(r.deidentified_fields||{})).toLowerCase().includes(search)})}
function ensureStyle(){if($('#nexaAuditPanelQueueStyle'))return;const s=document.createElement('style');s.id='nexaAuditPanelQueueStyle';s.textContent=`
#axBackMedical192{width:100%;height:38px;margin:10px 0 8px;border:1px solid var(--ax-line);border-radius:8px;background:var(--ax-panel);color:var(--ax-text);font-weight:900;text-align:left;padding:0 11px;cursor:pointer}
.ax-pq-state{display:grid;place-items:center;min-height:220px;text-align:center;color:var(--ax-muted)}
.ax-pq-error{border:1px solid rgba(255,88,114,.45);background:rgba(255,88,114,.08);color:var(--ax-text);border-radius:9px;padding:14px}.ax-pq-error button{margin-top:10px;height:34px;border:1px solid var(--ax-line);border-radius:7px;background:var(--ax-panel2);color:var(--ax-text);padding:0 12px;font-weight:800}
@media(max-width:900px){#axBackMedical192{display:block;margin:6px 0 10px}.ax-content{min-height:calc(100dvh - 120px)}}
`;document.head.appendChild(s)}
function ensureBack(){const side=$('#nexaAuditExact .ax-side');if(side&&!$('#axBackMedical192')){const b=document.createElement('button');b.id='axBackMedical192';b.textContent='← Voltar ao Modo Médico';side.querySelector('.ax-mode')?.insertAdjacentElement('afterend',b)}const top=$('#nexaAuditExact .ax-topbar');if(top&&!$('#axBackMedicalTop192')){const b=document.createElement('button');b.id='axBackMedicalTop192';b.textContent='← Médico';b.style.cssText='height:32px;margin-left:8px;border:1px solid var(--ax-line);border-radius:7px;background:var(--ax-panel);color:var(--ax-text);font-weight:850;padding:0 10px;cursor:pointer';top.appendChild(b)}}
function returnMedical(){$('#axReview')?.classList.remove('open');$('#nexaAuditExact')?.classList.remove('open');document.documentElement.style.overflow='';document.body.style.overflow='';window.scrollTo({top:0,behavior:'instant'});const target=$$('[data-mode="medical"],[data-work-mode="medical"],[data-mode="medico"],#n15Medico,#n9Medico').find(Boolean);try{target?.click()}catch{}}
function setActive(view){activeView=view;$$('#nexaAuditExact [data-ax-view]').forEach(b=>b.classList.toggle('active',b.dataset.axView===view));}
function renderPanel(){const c=counts(),done=c.approved+c.corrected,agree=done?Math.round(c.approved/done*100):0,avg=rows.length?Math.round(rows.reduce((a,r)=>a+coverage(r),0)/rows.length):0;const content=$('#axContent');if(!content)return;content.innerHTML=`<div class="ax-head"><div><h1>Painel de Auditoria</h1><p>Visão geral da qualidade, pendências e desempenho do NEXA.</p></div><button class="ax-range" data-pq-refresh>↻ Atualizar</button></div><section class="ax-kpis">${[['Pendentes',c.pending,'ax-red'],['Em revisão',0,'ax-orange'],['Aprovados',c.approved,'ax-green'],['Corrigidos',c.corrected,'ax-blue'],['Descartados',c.discarded,'']].map(([n,v,cl])=>`<div class="ax-kpi"><small>${n}</small><strong>${v}</strong><em class="${cl}">${n==='Pendentes'?'Fila atual':''}</em></div>`).join('')}</section><section class="ax-grid"><div class="ax-card"><h3>Taxa de concordância</h3><div class="ax-ring" style="--p:${agree}" data-v="${agree}%"></div></div><div class="ax-card"><h3>Qualidade documental</h3><div class="ax-ring" style="--p:${avg}" data-v="${avg}%"></div></div><div class="ax-card"><h3>Resumo operacional</h3><div class="ax-list"><div><span>Total recebido</span><b>${rows.length}</b></div><div><span>Casos concluídos</span><b>${done}</b></div><div><span>Pendentes</span><b>${c.pending}</b></div></div></div></section><section class="ax-queue"><div class="ax-queue-head"><h2>Fila de casos</h2><button class="ax-reviewbtn" data-pq-view="queue">Abrir fila completa</button></div>${renderTable(filtered().slice(0,5))}</section>`}
function renderTable(list){return `<div class="ax-table"><div class="ax-row head"><div>ID</div><div>Data/Hora</div><div>Modo</div><div>Queixa principal</div><div>Hipótese (IA)</div><div>Radar</div><div>Status</div><div>Ação</div></div>${list.map(r=>`<div class="ax-row"><div>#${esc(String(r.id).slice(0,5))}</div><div>${date(r.submitted_at)}</div><div>${mode(r)}</div><div>${esc(String(field(r,'queixa_principal')||field(r,'hda')||'Atendimento').slice(0,42))}</div><div>${esc(String(field(r,'hipotese_diagnostica')||'—').slice(0,36))}</div><div>${coverage(r)}%</div><div><span class="ax-status ${status(r)}">${statusText(status(r))}</span></div><div><button class="ax-reviewbtn" data-ax-open="${esc(r.id)}">Revisar</button></div></div>`).join('')||'<div class="ax-pq-state">Nenhum caso encontrado.</div>'}</div>`}
function renderQueue(){const c=counts(),list=filtered(),content=$('#axContent');if(!content)return;content.innerHTML=`<div class="ax-head"><div><h1>Fila de casos</h1><p>Consultas enviadas para auditoria.</p></div><button class="ax-range" data-pq-refresh>↻ Atualizar</button></div><section class="ax-queue"><div class="ax-queue-head"><div class="ax-filters">${[['all',`Todos (${rows.length})`],['pending',`Pendentes (${c.pending})`],['approved',`Aprovados (${c.approved})`],['corrected',`Corrigidos (${c.corrected})`],['discarded',`Descartados (${c.discarded})`]].map(([v,n])=>`<button class="ax-filter ${filter===v?'active':''}" data-pq-filter="${v}">${n}</button>`).join('')}</div></div>${renderTable(list)}</section>`}
function render(){setActive(activeView);if(activeView==='queue')renderQueue();else renderPanel()}
async function load(view=activeView){activeView=view;const content=$('#axContent');if(!content)return;content.innerHTML='<div class="ax-pq-state">Carregando Auditoria…</div>';try{const qv=await rpc('get_audit_queue',{queue_status:null});rows=[...(qv||[])].reverse();render()}catch(e){content.innerHTML=`<div class="ax-pq-error"><b>Não foi possível carregar a Auditoria.</b><div>${esc(e.message)}</div><button data-pq-retry>Tentar novamente</button></div>`}}
function bind(){document.addEventListener('click',e=>{const root=e.target.closest('#nexaAuditExact,#axReview');if(!root)return;const el=e.target.closest('button,a,[role="button"]');if(!el)return;if(el.id==='axBackMedical192'||el.id==='axBackMedicalTop192'){e.preventDefault();e.stopImmediatePropagation();returnMedical();return}const view=el.dataset?.axView;if(view==='panel'||view==='queue'){e.preventDefault();e.stopImmediatePropagation();load(view);return}const pv=el.dataset?.pqView;if(pv){e.preventDefault();load(pv);return}const f=el.dataset?.pqFilter;if(f){e.preventDefault();filter=f;renderQueue();return}if(el.matches('[data-pq-refresh],[data-pq-retry]')){e.preventDefault();load(activeView);return}},true);const input=$('#axSearch');if(input&&!input.dataset.pqBound){input.dataset.pqBound='1';input.addEventListener('input',()=>{search=input.value.trim().toLowerCase();if(activeView==='queue')renderQueue()})}}
function boot(){ensureStyle();ensureBack();bind();setTimeout(()=>{ensureBack();bind()},300);setTimeout(()=>ensureBack(),1000)}
boot();
window.nexaAuditorLoadPanel192=()=>load('panel');window.nexaAuditorLoadQueue192=()=>load('queue');window.nexaReturnToMedicalMode=returnMedical;
})();