/* NEXA v18.9.19 — offline-first persistent Audit outbox */
(()=>{
'use strict';
if(window.__NEXA_AUDIT_OUTBOX_V18_9_19__)return;
window.__NEXA_AUDIT_OUTBOX_V18_9_19__=true;
const DB='nexa-audit-outbox-v18919',STORE='items',ENCOUNTER_KEY='nexa-audit-open-encounter-v18919';
const RESET='#resetBtn,#nexaRadarResetBtn,#nfClear,#nfTopClear,#nexaNewCaseBtn,#nexaTopReset';
const AUDIT_SUBMIT_URL='https://fmkrcieubrlltiggyauc.supabase.co/functions/v1/submit-audit-case';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6ImZta3JjaWV1YnJsbHRpZ2d5YXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUwMTQzNjQsImV4cCI6MjEwMDU5MDM2NH0.lueZ5Czs3oHGXmQKNhw1egzuSBUOaMWpm3VoZucvIR4';
const SNAPSHOT_VERSION='final-v1',SEND_TIMEOUT_MS=12000,STALE_SENDING_MS=60000;
const KEYS=['queixa_principal','hda','comorbidades','antecedentes','medicacoes','alergias','hipotese_diagnostica','orientacoes_alta','sugestoes_perguntas','exame_fisico','conduta'];
let bypass=false,flushPromise=null,retryTimer=null,storeAdapter=null;
const clone=x=>{try{return structuredClone(x)}catch{return JSON.parse(JSON.stringify(x))}};
const uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const nowIso=()=>new Date().toISOString();
function currentAuth(){let access='',userId='';try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)||'';if(!key.includes('auth-token'))continue;const parsed=JSON.parse(localStorage.getItem(key)||'{}'),session=parsed?.currentSession||parsed?.session||parsed;if(session?.access_token){access=session.access_token;userId=session.user?.id||parsed?.user?.id||'';break}}}catch{}if(!userId)userId=String(window.currentProf?.id||'');return{access,userId:String(userId||'')}}
function owner(){return currentAuth().userId}
function field(k){return String(document.querySelector(`.field[data-key="${k}"] textarea`)?.value||'').trim()}
function collect(){const out={};for(const k of KEYS)out[k]=field(k);return out}
function valid(fields){const core=['queixa_principal','hda','exame_fisico','hipotese_diagnostica','conduta'].map(k=>String(fields?.[k]||'').trim()),meaningful=core.filter(v=>v.length>=5).length;return core[1].length>=20||(core[0].length>=5&&meaningful>=2)||meaningful>=3}
function redact(value){return String(value??'').replace(/\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b/g,'[E-MAIL REMOVIDO]').replace(/\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b/g,'[CPF REMOVIDO]').replace(/(?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-\s]?\d{4}\b/g,'[TELEFONE REMOVIDO]')}
function sanitize(fields){const out={};for(const[k,v]of Object.entries(fields||{})){if(/^(nome(?:_do)?_?paciente|patient_?name|cpf|rg|telefone|phone|celular|mobile|email|e_?mail|endereco|address|cep|documento|document_?id|patient_?id)$/i.test(k))continue;out[k]=typeof v==='string'?redact(v):Array.isArray(v)?v.map(x=>typeof x==='string'?redact(x):x):clone(v)}return out}
function destination(){try{return clone(window.nexaDestinationFlow18915?.state||{})}catch{return{}}}
function hypothesis(fields){return{ai:String(document.getElementById('aiHypothesisOriginal')?.textContent||'').trim(),final:String(document.getElementById('physicianHypothesis')?.value||fields.hipotese_diagnostica||'').trim(),cid:String(document.getElementById('physicianCid')?.value||'').trim()}}
function preferredHistoryId(){for(const candidate of [window.__NEXA_ACTIVE_HISTORY_ID__,window.nexaActiveHistoryId,document.documentElement?.dataset?.nexaHistoryId]){const id=String(candidate||'').trim();if(id)return id}return''}
function encounterStorageKey(userId){return`${ENCOUNTER_KEY}:${userId||'anon'}`}
function stableEncounterId(userId){const historyId=preferredHistoryId();if(historyId)return historyId;const key=encounterStorageKey(userId);let id='';try{id=sessionStorage.getItem(key)||''}catch{}if(!id){id=uuid();try{sessionStorage.setItem(key,id)}catch{}}return id}
function rotateEncounter(userId){try{sessionStorage.removeItem(encounterStorageKey(userId))}catch{}}
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE,{keyPath:'idempotency_key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('Falha ao abrir outbox.'))})}
async function idbGet(key){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close()})}
async function idbPut(item){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(clone(item));tx.oncomplete=()=>{db.close();resolve(clone(item))};tx.onerror=()=>{db.close();reject(tx.error||new Error('Falha ao persistir outbox.'))}})}
async function idbAll(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close()})}
const store={get:key=>storeAdapter?.get?storeAdapter.get(key):idbGet(key),put:item=>storeAdapter?.put?storeAdapter.put(clone(item)):idbPut(item),all:()=>storeAdapter?.all?storeAdapter.all():idbAll()};
async function buildSnapshot(reason='reset_safety_net'){const raw=collect();if(!valid(raw))return null;const who=owner();if(!who)throw new Error('Sessão clínica não identificada.');const source=stableEncounterId(who),version=SNAPSHOT_VERSION,key=`${source}:${version}`,captured=nowIso(),fields=sanitize(raw),h=hypothesis(fields),dest=destination();const payload={source_consultation_id:source,snapshot_version:version,idempotency_key:key,fields,core_context:{schema_version:'3',hypothesis_validation:{status:'reviewed',ai:h.ai,final:h.final,cid:h.cid},destination:dest,learning_layers:{original_ai:{hypothesis:h.ai},physician_final:{hypothesis:h.final,cid:h.cid,destination:clone(dest)},audit_corrected:null},audit_submission_snapshot:{captured_at:captured,source_consultation_id:source,snapshot_version:version,idempotency_key:key,immutable_submission:true,capture_reason:reason,frontend_version:'18.9.19'}}};return{local_submission_id:uuid(),idempotency_key:key,source_consultation_id:source,snapshot_version:version,owner_user_id:who,captured_at:captured,state:'queued',attempt_count:0,last_attempt_at:null,next_attempt_at:null,last_error:null,payload:clone(payload)}}
async function enqueue(item){const existing=await store.get(item.idempotency_key);if(existing){window.dispatchEvent(new CustomEvent('nexa:audit-submission-deduplicated',{detail:{idempotency_key:item.idempotency_key}}));return clone(existing)}const persisted=await store.put(clone(item));window.dispatchEvent(new CustomEvent('nexa:audit-snapshot-created',{detail:{idempotency_key:item.idempotency_key}}));window.dispatchEvent(new CustomEvent('nexa:audit-outbox-queued',{detail:{idempotency_key:item.idempotency_key}}));return persisted}
async function preserve(reason){const snap=await buildSnapshot(reason);return snap?enqueue(snap):null}
function authHeaders(){const{access}=currentAuth();if(!access)throw new Error('Sessão do NEXA Core indisponível.');return{Authorization:`Bearer ${access}`,apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'}}
function backoff(attempt){const base=Math.min(300000,5000*Math.pow(2,Math.max(0,attempt-1))),jitter=Math.floor(Math.random()*Math.min(3000,Math.max(500,base*.15)));return base+jitter}
function due(item,now=Date.now()){const next=item?.next_attempt_at?new Date(item.next_attempt_at).getTime():0;return!next||next<=now}
async function sendItem(item){const auth=currentAuth();if(!auth.userId||auth.userId!==String(item.owner_user_id||''))return{skipped:true};const attempt=Number(item.attempt_count||0)+1,start=nowIso();let working={...clone(item),state:'sending',attempt_count:attempt,last_attempt_at:start,last_error:null};await store.put(working);window.dispatchEvent(new CustomEvent('nexa:audit-submission-started',{detail:{idempotency_key:item.idempotency_key,attempt}}));const controller=new AbortController(),timer=setTimeout(()=>controller.abort('audit-timeout'),SEND_TIMEOUT_MS);try{const response=await fetch(AUDIT_SUBMIT_URL,{method:'POST',headers:authHeaders(),body:JSON.stringify(clone(item.payload)),signal:controller.signal}),data=await response.json().catch(()=>({}));if(!response.ok&&data?.error!=='ALREADY_SUBMITTED')throw new Error(data?.error||`HTTP_${response.status}`);working={...working,state:'sent',sent_at:nowIso(),next_attempt_at:null,last_error:null,server_result:data?.error==='ALREADY_SUBMITTED'?'ALREADY_SUBMITTED':'accepted'};await store.put(working);window.dispatchEvent(new CustomEvent('nexa:audit-submission-success',{detail:{idempotency_key:item.idempotency_key,idempotent:data?.error==='ALREADY_SUBMITTED'}}));return{sent:true,item:working}}catch(error){const message=error?.name==='AbortError'||String(error||'').includes('audit-timeout')?'TIMEOUT':String(error?.message||error||'NETWORK_ERROR'),wait=backoff(attempt);working={...working,state:'queued',last_error:message,next_attempt_at:new Date(Date.now()+wait).toISOString()};await store.put(working);window.dispatchEvent(new CustomEvent('nexa:audit-submission-failed',{detail:{idempotency_key:item.idempotency_key,error:message,attempt}}));return{sent:false,error:message,item:working}}finally{clearTimeout(timer)}}
async function recoverStale(items){const t=Date.now();for(const item of items){if(item.state==='sending'&&t-new Date(item.last_attempt_at||0).getTime()>STALE_SENDING_MS)await store.put({...item,state:'queued',last_error:'RECOVERED_STALE_SENDING',next_attempt_at:null})}}
function scheduleRetry(items){clearTimeout(retryTimer);retryTimer=null;const auth=currentAuth();if(!auth.userId)return;const times=items.filter(x=>x.owner_user_id===auth.userId&&x.state!=='sent'&&x.next_attempt_at).map(x=>new Date(x.next_attempt_at).getTime()).filter(Number.isFinite);if(!times.length)return;const delay=Math.max(500,Math.min(...times)-Date.now());retryTimer=setTimeout(()=>flush('scheduled_retry'),Math.min(delay,300000))}
async function flush(reason='manual'){if(flushPromise)return flushPromise;flushPromise=(async()=>{const auth=currentAuth();if(!auth.userId||!auth.access)return{sent:0,pending:0,reason:'no_session'};let items=await store.all();await recoverStale(items);items=await store.all();let sent=0;for(const item of items.filter(x=>x.owner_user_id===auth.userId&&x.state!=='sent'&&due(x))){const result=await sendItem(item);if(result.sent)sent++}items=await store.all();scheduleRetry(items);return{sent,pending:items.filter(x=>x.owner_user_id===auth.userId&&x.state!=='sent').length,reason}})().finally(()=>{flushPromise=null});return flushPromise}
function toast(msg,bad=false){let x=document.getElementById('nexaAuditOutboxToast');if(!x){x=document.createElement('div');x.id='nexaAuditOutboxToast';x.style.cssText='position:fixed;z-index:40000;right:16px;bottom:92px;max-width:440px;padding:10px 12px;border-radius:10px;font:800 11px/1.35 system-ui;box-shadow:0 10px 28px rgba(0,0,0,.2)';document.body.appendChild(x)}x.textContent=msg;x.style.background=bad?'#fff0f1':'#eaf8f4';x.style.color=bad?'#8e2931':'#086f61';clearTimeout(x.__t);x.__t=setTimeout(()=>x.remove(),4200)}
async function ensureAuditSnapshotBeforeReset(){return preserve('reset_safety_net')}
function performReset(target){const core=document.getElementById('resetBtn')||target,originalConfirm=window.confirm;try{window.confirm=()=>true;if(typeof core?.onclick==='function')core.onclick.call(core)}finally{window.confirm=originalConfirm}bypass=true;try{if(core?.click){const nativeOnclick=core.onclick;core.onclick=null;core.click();core.onclick=nativeOnclick}if(target&&target!==core)target.click()}finally{queueMicrotask(()=>{bypass=false})}}
async function beforeReset(el){const who=owner();try{const fields=collect(),hasValid=valid(fields);if(hasValid&&typeof window.confirm==='function'&&!window.confirm('Finalizar esta consulta? O NEXA vai preservar o snapshot localmente antes de limpar.'))return;const snap=hasValid?await ensureAuditSnapshotBeforeReset():null;if(snap)toast('Atendimento preservado localmente para Auditoria.');performReset(el);rotateEncounter(who);void flush('reset')}catch(error){toast(`Atendimento não apagado: ${error?.message||error}`,true)}}
async function manual(button){try{const snap=await preserve('manual_early_submit');if(!snap)return toast('Não há conteúdo clínico suficiente para Auditoria.',true);toast('Snapshot preservado na fila de Auditoria.');void flush('manual_submit');if(button){const text=button.textContent;button.textContent='Enfileirada ✓';setTimeout(()=>{button.textContent=text},1500)}}catch(error){toast(error?.message||'Falha ao preservar snapshot.',true)}}
function bind(){document.addEventListener('click',event=>{const reset=event.target?.closest?.(RESET);if(reset){if(bypass){event.stopImmediatePropagation();return}event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();beforeReset(reset);return}const manualButton=event.target?.closest?.('#submitAuditBtn');if(manualButton){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();manual(manualButton)}},true);addEventListener('online',()=>void flush('online'));addEventListener('focus',()=>void flush('focus'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)void flush('visible')});addEventListener('nexa:audit-outbox-flush-request',()=>void flush('event'));setTimeout(()=>void flush('startup'),1200)}
bind();window.ensureAuditSnapshotBeforeReset=ensureAuditSnapshotBeforeReset;window.nexaAuditOutbox18919={buildSnapshot,snapshot:buildSnapshot,preserve,enqueue,flush,sendItem,get:store.get,put:store.put,all:store.all,valid,sanitize,owner,stableEncounterId,rotateEncounter,currentAuth,backoff,due,performReset,setStoreAdapter:adapter=>{storeAdapter=adapter||null},constants:{DB,STORE,SNAPSHOT_VERSION,SEND_TIMEOUT_MS,STALE_SENDING_MS,AUDIT_SUBMIT_URL}};
})();
