// Synthetic external services for browser regression. Never included by the production build.
(()=>{
 let session={access_token:'synthetic-token',user:{id:'qa-physician-a',email:'qa@example.invalid',user_metadata:{display_name:'Médico QA'}}},authChange;
 const qa=window.__qa={requests:[],channels:[],clipboard:'',failRadar:false,denyCapabilities:false,capabilities:{access_status:'active',clinical_access:true,is_admin:false,is_reviewer:false,display_name:'Médico QA'},auditDecisions:[]};
 qa.auditRows=[
  {id:'33333333-3333-4333-8333-333333333331',source_consultation_id:'44444444-4444-4444-8444-444444444441',status:'pending',priority:1,submitted_at:'2026-09-25T10:00:00Z',deidentified_fields:{queixa_principal:'CASO QA A',hda:'HISTÓRICO SINTÉTICO A',hipotese_diagnostica:'HIPÓTESE QA A',conduta:'CONDUTA QA A',cid:'J45'},deidentified_core_context:{case_mode:'upper',learning_layers:{original_ai:{fields:{hda:'ORIGINAL QA A'},hypothesis:'IA QA A'},physician_final:{fields:{hda:'FINAL QA A',hipotese_diagnostica:'HIPÓTESE QA A'}},audit_corrected:null}}},
  {id:'33333333-3333-4333-8333-333333333332',source_consultation_id:'44444444-4444-4444-8444-444444444442',status:'pending',priority:0,submitted_at:'2026-09-25T11:00:00Z',deidentified_fields:{queixa_principal:'CASO QA B',hda:'HISTÓRICO SINTÉTICO B',hipotese_diagnostica:'HIPÓTESE QA B',conduta:'CONDUTA QA B'},deidentified_core_context:{case_mode:'upper',learning_layers:{original_ai:{fields:{hda:'ORIGINAL QA B'}},physician_final:{fields:{hda:'FINAL QA B'}},audit_corrected:null}}},
  {id:'33333333-3333-4333-8333-333333333333',source_consultation_id:'44444444-4444-4444-8444-444444444443',status:'pending',priority:0,submitted_at:'2026-09-25T12:00:00Z',deidentified_fields:{queixa_principal:'CASO QA C',hda:'HISTÓRICO SINTÉTICO C',hipotese_diagnostica:'HIPÓTESE QA C',conduta:'CONDUTA QA C'},deidentified_core_context:{case_mode:'upper',learning_layers:{original_ai:{fields:{hda:'ORIGINAL QA C'}},physician_final:{fields:{hda:'FINAL QA C'}},audit_corrected:null}}}
 ];
 const empty=()=>{const chain={then:resolve=>Promise.resolve({data:[],error:null}).then(resolve)};for(const k of ['select','eq','gte','order','limit','update','insert','delete','upsert','maybeSingle','single','in'])chain[k]=()=>chain;return chain;};
 window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session}}),onAuthStateChange:fn=>{authChange=fn;return {data:{subscription:{unsubscribe(){}}}}},signOut:async()=>{session=null;localStorage.removeItem('sb-synthetic-auth-token');authChange?.('SIGNED_OUT',null);return {error:null};}},rpc:async name=>qa.denyCapabilities?{error:{message:'Unavailable'}}:{data:name==='get_my_capabilities'?[{...qa.capabilities}]:[],error:null},from:empty,functions:{invoke:async(slug,{body}={})=>{const res=await fetch('https://synthetic.supabase.co/functions/v1/'+slug,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});const data=await res.json().catch(()=>null);return res.ok?{data,error:null}:{data:null,error:{message:data?.error||'Function error',context:{status:res.status}}}}}})};
 const persistSession=()=>localStorage.setItem('sb-synthetic-auth-token',JSON.stringify(session));persistSession();
 qa.switchUser=id=>{session={...session,user:{id,email:'qa@example.invalid'}};persistSession();authChange?.('SIGNED_IN',session);};
 qa.speak=(id,transcript,index=qa.channels.length-1)=>{const channel=qa.channels[index];channel.receive?.({data:JSON.stringify({type:'conversation.item.input_audio_transcription.completed',item_id:id,transcript})});};
 window.RTCPeerConnection=class {addTrack(track){qa.track=track;}createDataChannel(){const channel={close(){this.onclose?.();},send(){}};Object.defineProperty(channel,'onmessage',{set(fn){this.handler=fn;if(fn)this.receive=fn;},get(){return this.handler;}});qa.channels.push(channel);return this.channel=channel;}async createOffer(){return {sdp:'synthetic'};}async setLocalDescription(){}async setRemoteDescription(){this.channel.onopen?.();}close(){}};
 Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{qa.clipboard=text;}}});
 const nativeFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{
 const url=String(input?.url||input);if(url.includes('.supabase.co')){
  qa.requests.push({url,method:init.method,body:typeof init.body==='string'?init.body:null});
  if(url.includes('/rpc/get_my_capabilities'))return qa.denyCapabilities?Response.json({error:'Unavailable'},{status:503}):Response.json([{...qa.capabilities}]);
  if(url.includes('/rpc/get_audit_queue_v2')||url.includes('/rpc/get_audit_queue'))return Response.json(qa.auditRows);
  if(url.includes('/rpc/get_audit_dashboard')){const c={pending:0,approved:0,corrected:0,discarded:0};qa.auditRows.forEach(r=>c[r.status]=(c[r.status]||0)+1);const completed=c.approved+c.corrected+c.discarded;return Response.json([{total_received:qa.auditRows.length,...c,completed,agreement_rate:(c.approved+c.corrected)?Math.round(100*c.approved/(c.approved+c.corrected)):0,documentation_quality:80}]);}
  if(url.includes('/rpc/get_core_dataset_summary'))return Response.json([{total_cases:qa.auditRows.filter(r=>['approved','corrected'].includes(r.status)).length,approved_cases:qa.auditRows.filter(r=>r.status==='approved').length,corrected_cases:qa.auditRows.filter(r=>r.status==='corrected').length,documentation_ready_cases:qa.auditRows.filter(r=>['approved','corrected'].includes(r.status)).length,clinical_plan_ready_cases:0,radar_ready_cases:0,last_published_at:null}]);
  if(url.includes('/rpc/submit_audit_review')){const body=JSON.parse(init.body||'{}'),row=qa.auditRows.find(r=>r.id===body.case_id);if(!row)return Response.json({message:'AUDIT_CASE_NOT_FOUND'},{status:404});if(row.status!=='pending')return Response.json({message:'AUDIT_REVIEW_CONFLICT'},{status:409});if(body.decision==='discarded'&&!String(body.note||'').trim())return Response.json({message:'DISCARD_REASON_REQUIRED'},{status:400});row.status=body.decision;row.reviewed_fields=body.decision==='corrected'?body.corrected_fields:body.decision==='approved'?row.deidentified_fields:null;row.review_note=body.note||null;row.reviewed_at=new Date().toISOString();qa.auditDecisions.push({case_id:body.case_id,decision:body.decision,note:body.note||null,corrected_fields:body.corrected_fields||null});return Response.json(null);}
  if(url.includes('realtime-call'))return Response.json(init.body instanceof FormData?{text:'Cefaleia. Nega febre.'}:{sdp:'synthetic'});
  if(url.includes('realtime-radar'))return qa.failRadar?Response.json({error:'unavailable'},{status:503}):Response.json({items:[],observations:[]});
  if(url.includes('process-consultation'))return Response.json({fields:{queixa_principal:'Cefaleia',hda:'Cefaleia desde hoje. A dor começou de repente. Nega febre. Sem demais queixas.',alergias:'Nega alergias.',comorbidades:'Nega comorbidades.',medicacoes:'Nega uso contínuo.',antecedentes:'Sem antecedentes informados.',exame_fisico:'Exame em avaliação.',hipotese_diagnostica:'Cefaleia a esclarecer — R51',conduta:''},model:'synthetic',provider:'test'});
  if(url.includes('clinical-assistant'))return Response.json({answer:'{"destination":"em_avaliacao","reason":"Dados insuficientes no caso sintético"}'});
  if(url.includes('clinical-plan'))return Response.json({exames:[{nome:'Exame de teste',justificativa:'Caso sintético'}],prescricao:[{principio_ativo:'Medicamento QA sem uso clínico',apresentacao:'apresentação sintética',quantidade_total:'1 item de teste',via:'oral',manual_text:'Texto sintético para validar cópia, sem finalidade clínica.',sugerido:true}],orientacoes_alta:['Orientação de teste'],condutas:['Reavaliar o caso sintético.']});
  if(url.includes('protocol-library'))return Response.json({items:[{id:'11111111-1111-4111-8111-111111111111',title:'Condição QA',diagnosis_key:'condicao-qa',cid10:['J45'],match_terms:['condição qa','termo qa'],version:{id:'22222222-2222-4222-8222-222222222222',version_no:3,clinical_scope:'Contexto sintético QA.',source_label:'Fonte sintética QA',source_page:'1',prescription_text:'',prescription_items:[{principio_ativo:'ITEM QA',apresentacao:'FORMATO QA',quantidade_total:'QTD QA',via:'outra',manual_text:'INSTRUÇÃO SINTÉTICA QA',categoria:'QA',sugerido:true}],guidance_text:'Orientação sintética QA.',criteria_text:'Critério sintético QA.',contraindications_text:'Texto sintético QA.',required_data_text:'Dados sintéticos QA.',published_at:'2026-09-25T00:00:00Z'}}],total:1});
  return Response.json([]);
 }return nativeFetch(input,init);
 };
})();
