import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const loader=read('nexa-hotfix.js');
const layout=read('nexa-layout-static-v18.6.5.js');
const audit=read('nexa-audit-autosave-v18.5.js');
const draft=read('nexa-record-draft-history-v18.6.6.js');
const mobile=read('nexa-mobile-shell-v18.6.7.js');
const historyLifecycle=read('nexa-history-lifecycle-v18.6.9.js');
const mobileFlow=read('nexa-mobile-flow-v18.8.1.js');
const exact=read('nexa-auditor-exact-v18.9.js');
const functional=read('nexa-auditor-functional-v18.9.1.js');
const html=read('index.html');
const sw=read('sw.js');
const required=['nexa-hotfix-v1.js','nexa-ui-v3.js','nexa-radar-v4.js','nexa-final-ui-v18.js','nexa-layout-static-v18.6.5.js','nexa-audit-autosave-v18.5.js','nexa-record-draft-history-v18.6.6.js','nexa-mobile-shell-v18.6.7.js','nexa-history-lifecycle-v18.6.9.js','nexa-mobile-flow-v18.8.1.js','nexa-auditor-exact-v18.9.js','nexa-auditor-functional-v18.9.1.js'];
for(const mod of required)assert.ok(loader.includes(mod),`loader sem ${mod}`);
for(const forbidden of ['nexa-auditor-native-v18.8.js','nexa-auditor-workspace-v18.7.js','nexa-auditor-mobile-fix-v18.7.1.js','nexa-mobile-safe-area-v18.6.8.js','nexa-mobile-top-safe-v18.8.js'])assert.ok(!loader.includes(forbidden),`loader não pode carregar camada antiga/conflitante: ${forbidden}`);
assert.ok(loader.includes('20260905-v1891'));
assert.ok(loader.lastIndexOf('nexa-auditor-functional-v18.9.1.js')>loader.lastIndexOf('nexa-auditor-exact-v18.9.js'),'patch funcional deve carregar por último');
for(const id of ['recBtn','consent','timer','processBtn','resetBtn','workspaceHistoryPane','submitAuditBtn'])assert.ok(html.includes(`id="${id}"`));
assert.ok(html.includes("$('submitAuditBtn').onclick=submitCurrentForAudit"));
assert.ok(html.includes("Date.now()-7*24*60*60*1000"));
assert.ok(!layout.includes('MutationObserver')&&!layout.includes('setInterval'));
for(const token of ['__NEXA_AUDIT_AUTOSAVE_V18_5__','archiveCurrentCase','automatic_audit_handoff:true','retryQueue'])assert.ok(audit.includes(token));
for(const token of ['__NEXA_RECORD_DRAFT_HISTORY_V18_6_6__',"rec.dataset.nexaStartOnly='1'",'window.nexaRefreshDraftHistory'])assert.ok(draft.includes(token));
for(const token of ['__NEXA_MOBILE_SHELL_V18_6_7__','nexaMobileBottomNav','nexaMobileHeader'])assert.ok(mobile.includes(token));
for(const token of ['__NEXA_HISTORY_LIFECYCLE_V18_6_9__','Consultas dos últimos 7 dias','Enviar p/ auditoria'])assert.ok(historyLifecycle.includes(token));
for(const token of ['__NEXA_MOBILE_FLOW_V18_8_1__','position:sticky!important','document.body.insertBefore(header,app)'])assert.ok(mobileFlow.includes(token));
for(const token of ['__NEXA_AUDITOR_EXACT_V18_9__','Painel de Auditoria','Fila de casos','Taxa de concordância','Principais campos com correções','Aprovar sem alteração','Aprovar com correções','Descartar do aprendizado','get_audit_queue','get_core_dataset_summary','submit_audit_review','nexaOpenProfessionalAuditExact',"mobileOpen==='audit'",'#nexaMobileDrawer{top:calc(116px'])assert.ok(exact.includes(token),`auditor exato sem ${token}`);
for(const token of ['__NEXA_AUDITOR_FUNCTIONAL_V18_9_1__','Voltar ao Modo Médico','nexaReturnToMedicalMode','nexaRefreshAuditExact','get_audit_queue','get_core_dataset_summary','ax-correctok','ax-correct','ax-problem','renderStats','renderLearning','navigateCase'])assert.ok(functional.includes(token),`patch funcional sem ${token}`);
assert.ok(!exact.includes('new MutationObserver')&&!exact.includes('setInterval'),'auditor exato não pode usar loops contínuos');
assert.ok(!functional.includes('new MutationObserver')&&!functional.includes('setInterval'),'patch funcional não pode usar loops contínuos');
assert.ok(sw.includes('nexa-v18-9-1-functional-auditor-20260905'));
assert.ok(sw.includes('20260905-v1891'));
assert.ok(sw.includes('cache:"no-store"'));
new Function(loader);new Function(layout);new Function(audit);new Function(draft);new Function(mobile);new Function(historyLifecycle);new Function(mobileFlow);new Function(exact);new Function(functional);new Function(sw);
console.log('NEXA v18.9.1 exact + functional auditor: PASS');
