const {test}=require('node:test');const assert=require('node:assert/strict');const E=require('../nexa-radar-engine');
const context=(hda,fields={})=>({fields:{hda,...fields}});
const result=(text,fields)=>E.analyze(context(text,fields));const has=(r,id)=>r.items.some(i=>i.id===id);
test('A: ankle pain identifies trauma gap',()=>assert.ok(has(result('Dor no tornozelo esquerdo há dois dias.'),'trauma')));
test('B: established sprain advances to mechanism and exam',()=>{const r=result('Dor no tornozelo esquerdo após entorse jogando futebol.');assert.ok(!has(r,'trauma'));assert.ok(has(r,'fourSteps'));assert.ok(has(r,'neurovascular'));});
test('C: measured fever is not missing temperature',()=>assert.ok(!has(result('Febre de 38,5 °C.'),'temperature')));
test('D: unmeasured reported fever',()=>{const r=result('Refere febre, não aferiu temperatura.');assert.ok(!has(r,'temperature'));assert.equal(r.facts.fever.state,'known_present');});
test('E: negative fever does not activate fever pack',()=>{const r=result('Nega febre.');assert.ok(!has(r,'temperature'));assert.equal(r.facts.fever.state,'known_absent');});
test('F: chest red flags rank above characterization',()=>{const r=result('Dor torácica.');assert.ok(has(r,'dyspnea'));assert.equal(r.items[0].priority,'critical');});
test('G: coordinated negation respects all three symptoms',()=>{const r=result('Dor torácica, nega dispneia, síncope e sudorese.');for(const id of ['dyspnea','syncope','sweating']){assert.ok(!has(r,id));assert.equal(r.facts[id].state,'known_absent');}});
test('H: response enters history once, activates trauma details',()=>{const c=context('Dor no tornozelo esquerdo há dois dias.');const item=E.analyze(c).items.find(i=>i.id==='trauma');const r=E.answer(c,{},item,'Sim, queda da própria altura ontem.');const next=E.analyze(r.context,r.ledger);assert.ok(!has(next,'trauma'));assert.ok(has(next,'fourSteps'));assert.equal(r.context.fields.hda.match(/queda da própria altura/g).length,1);const twice=E.answer(r.context,r.ledger,item,'Sim, queda da própria altura ontem.');assert.equal(twice.context.fields.hda,r.context.fields.hda);});
test('I: contradictory fever requires clarification',()=>assert.ok(has(result('Nega febre. Teve febre de 39 °C em casa.'),'conflict:fever')));
test('resolved fever preserves temporal distinction',()=>{const r=result('Teve febre há três dias, mas está afebril há 48 horas.');assert.ok(!has(r,'conflict:fever'));assert.equal(r.facts.fever.temporal,'resolved');});
test('old trauma from history does not activate current trauma',()=>{const r=result('Dor no tornozelo.',{antecedentes:'Queda há 10 anos.'});assert.ok(has(r,'trauma'));assert.ok(!has(r,'mechanism'));});
test('hypothesis cannot hide peritonism gap',()=>{const r=result('Dor abdominal localizada com febre.',{hipotese_diagnostica:'Gastroenterite'});assert.equal(r.stage,'post_hypothesis');assert.ok(has(r,'peritonism'));});
test('filled template placeholders do not count as vital signs',()=>{const r=result('Dor torácica.',{exame_fisico:'PA: mmHg // FC: BPM // SatO2: %'});assert.ok(has(r,'bp'));assert.ok(has(r,'hr'));assert.ok(has(r,'spo2'));});
test('measured vitals in exam remove only measured gaps',()=>{const r=result('Dor torácica.',{exame_fisico:'PA: 120/80 mmHg; FC: 80 bpm; SatO2: 98%.'});for(const id of ['bp','hr','spo2'])assert.ok(!has(r,id));assert.ok(has(r,'dyspnea'));});
test('affirmative clause terminates negation',()=>{const r=result('Nega febre, mas apresenta dispneia.');assert.equal(r.facts.dyspnea.state,'known_present');});
test('exam response enters exam, not HDA',()=>{const c=context('Entorse de tornozelo.');const i=E.analyze(c).items.find(i=>i.id==='neurovascular');const r=E.answer(c,{},i,'Pulsos presentes, sensibilidade e motricidade preservadas');assert.equal(r.context.fields.hda,c.fields.hda);assert.match(r.context.fields.exame_fisico,/Pulsos presentes/);assert.ok(!has(E.analyze(r.context,r.ledger),'neurovascular'));});
test('vital response enters vitals',()=>{const c=context('Dor torácica.');const i=E.analyze(c).items.find(i=>i.id==='bp');const r=E.answer(c,{},i,'120/80 mmHg');assert.match(r.context.fields.sinais_vitais,/120\/80/);});
test('dismissal does not invent normal findings',()=>{const c=context('Dor torácica.');const i=E.analyze(c).items.find(i=>i.id==='dyspnea');const r=E.answer(c,{},i,'Já avaliado','evaluated');assert.deepEqual(r.context.fields,c.fields);assert.ok(!has(E.analyze(r.context,r.ledger),'dyspnea'));});
test('unknown is distinct from negative',()=>{const c=context('Dor torácica.');const i=E.analyze(c).items.find(i=>i.id==='dyspnea');const r=E.answer(c,{},i,'Não sabe informar');assert.equal(E.analyze(r.context,r.ledger).facts.dyspnea.state,'unknown');});
test('new evidence revives a contradiction after dismissal',()=>{const c=context('Nega febre. Refere febre.');const i=E.analyze(c).items.find(i=>i.id==='conflict:fever');const r=E.answer(c,{},i,'Dispensar','dismissed');r.context.fields.hda+=' Teve febre de 39 °C.';assert.ok(has(E.analyze(r.context,r.ledger),'conflict:fever'));});
test('AI cannot remove deterministic red flags or turn findings into fact',()=>{const c=context('Dor torácica.');const r=E.analyze(c,{},[{concept:'dyspnea',priority:'low',question:'Paciente com dispneia',contextEvidence:'Dor torácica.'}]);assert.equal(r.items.find(i=>i.id==='dyspnea').priority,'critical');assert.ok(!JSON.stringify(r.items).includes('Paciente com dispneia'));assert.equal(r.facts.dyspnea.state,'not_asked');});
test('AI unsupported evidence rejected',()=>{const r=E.analyze(context('Dor torácica.'),{},[{concept:'saddle',contextEvidence:'Lombalgia'}]);assert.ok(!has(r,'saddle'));});
test('new encounter with empty ledger carries no answers',()=>{const r=E.analyze(context('Dor torácica.'),{});assert.ok(has(r,'dyspnea'));});
const cases=[['dor torácica','Dor torácica.','dyspnea'],['dor abdominal','Dor abdominal.','peritonism'],['cefaleia','Cefaleia.','sudden'],['lombalgia','Lombalgia.','saddle'],['trauma','Queda da própria altura.','neurovascular'],['urinários','Disúria há dois dias.','flank'],['respiratórios','Tosse há três dias.','spo2'],['febre','Febre.','temperature'],['membro','Dor em perna esquerda.','pulses'],['neurológico','Tontura desde ontem.','focal']];
for(const [name,text,id] of cases)test('simulated case: '+name,()=>{const r=result(text);assert.ok(has(r,id));assert.equal(new Set(r.items.map(i=>i.id)).size,r.items.length);assert.ok(r.items.every(i=>i.question.startsWith('Investigar')||i.question.startsWith('Esclarecer')));});

test('conversation: a question is not a patient finding',()=>{const r=E.analyze({transcript:'Cefaleia desde hoje. Médico: Teve febre?'});assert.equal(r.facts.fever.state,'not_asked');assert.equal(r.items.find(i=>i.id==='fever').status,'asked');assert.equal(r.alerts.length,0);});
test('conversation: isolated answer resolves the preceding boolean question',()=>{const r=E.analyze({transcript:'Cefaleia desde hoje. Médico: Teve febre? Paciente: Não.'});assert.equal(r.facts.fever.state,'known_absent');assert.ok(!has(r,'fever'));assert.ok(r.clarified.some(i=>i.id==='fever'));});
test('conversation: answering a sudden onset question reveals an enduring alert',()=>{const r=E.analyze({transcript:'Cefaleia desde hoje. Médico: A dor começou de repente? Paciente: Sim.'});assert.equal(r.facts.sudden.state,'known_present');assert.ok(!has(r,'sudden'));assert.ok(r.alerts.some(i=>i.concept==='sudden'));assert.match(r.alerts[0].evidence[0].questionQuote,/de repente/);});
test('conversation: ambiguous and compound answers require confirmation',()=>{for(const transcript of ['Dor torácica. Médico: Teve dispneia e síncope? Paciente: Não.','Dor torácica. Médico: Teve dispneia? Paciente: Talvez.']){const r=E.analyze({transcript});assert.equal(r.items.find(i=>i.concept==='dyspnea').status,'confirm');assert.notEqual(r.facts.dyspnea.state,'known_absent');}});
test('conversation: third-party symptoms do not become patient symptoms',()=>{const r=E.analyze({transcript:'Cefaleia. Minha mãe teve febre de 39 °C.'});assert.equal(r.facts.fever.state,'not_asked');assert.equal(r.facts.temperature.state,'not_asked');});
test('conversation: unsolicited answers clear pending information without manual entry',()=>{const r=E.analyze({transcript:'Dor torácica. Não tive desmaio. Nega falta de ar. PA 120/80.'});for(const id of ['syncope','dyspnea','bp'])assert.ok(!has(r,id));});
test('conversation: explicit correction supersedes old version but new conflict reopens',()=>{const initial='Cefaleia. Nega febre. Corrigindo, febre de 39 °C em casa.';const r=E.analyze({transcript:initial});assert.equal(r.facts.fever.conflict,false);assert.equal(r.facts.fever.state,'known_present');assert.ok(has(E.analyze({transcript:initial+' Nega febre.'}),'conflict:fever'));});
test('conversation: initial and present ability to walk are separate gaps',()=>{const r=E.analyze({transcript:'Entorse de tornozelo. Consegue dar quatro passos agora.'});assert.ok(!has(r,'fourSteps'));assert.ok(has(r,'weightThen'));});
test('AI interpretation is evidence bound and cannot use a question as an answer',()=>{const c={transcript:'Dor torácica. Teve falta de ar?'};const o={concept:'dyspnea',subject:'patient',section:'transcript',quote:'Teve falta de ar?',state:'known_absent',temporal:'current'};assert.equal(E.analyze(c,{},[],[o]).facts.dyspnea.state,'not_asked');o.quote='Nega dispneia';assert.equal(E.analyze(c,{},[],[o]).facts.dyspnea.state,'not_asked');});
test('AI interpretation expands language with a literal source without writing a finding to the record',()=>{const c={fields:{hda:'Dor torácica. O ar não entra direito.'}};const r=E.analyze(c,{},[],[{concept:'dyspnea',subject:'patient',section:'hda',quote:'O ar não entra direito.',state:'known_present',temporal:'current'}]);assert.equal(r.facts.dyspnea.state,'known_present');assert.equal(c.fields.hda,'Dor torácica. O ar não entra direito.');assert.ok(r.alerts.some(i=>i.concept==='dyspnea'));});
test('unknown AI interpretation never provides reassuring negation',()=>{const c={transcript:'Dor torácica. Acho que não tive falta de ar.'};const r=E.analyze(c,{},[],[{concept:'dyspnea',subject:'patient',section:'transcript',quote:'Acho que não tive falta de ar.',state:'known_absent',temporal:'current'}]);assert.equal(r.facts.dyspnea.state,'unknown');});

test('conversation: yes does not resolve a question with alternative answers',()=>{const r=E.analyze({transcript:'Cefaleia. A dor começou de repente ou aos poucos? Sim.'});assert.equal(r.facts.sudden.state,'unknown');assert.equal(r.alerts.length,0);});
test('AI cannot evade question or third-party exclusion by shortening its quote',()=>{for(const transcript of ['Cefaleia. Médico: Teve febre?','Cefaleia. Minha mãe teve febre.']){const r=E.analyze({transcript},{},[],[{concept:'fever',subject:'patient',section:'transcript',quote:'teve febre',state:'known_present',temporal:'current'}]);assert.equal(r.facts.fever.state,'not_asked');}});

test('spontaneous sudden onset and affirmative trauma are findings, not questions',()=>{const E=require('../nexa-radar-engine');const s=E.analyze({transcript:'Cefaleia desde hoje. Médico: Teve febre?\nPaciente: Não.\nA dor começou de repente. Houve trauma ontem.'});assert.equal(s.facts.sudden.state,'known_present');assert.equal(s.facts.trauma.state,'known_present');assert.ok(s.alerts.some(a=>a.concept==='sudden'));assert.ok(!s.items.some(i=>i.concept==='trauma'));});

test('consciousness: abnormal findings persist while normal and invalid results do not become alarms',()=>{
 for(const quote of ['Confusão mental.','Glasgow 14.','Rebaixamento de consciência.']){const r=E.analyze({transcript:'Cefaleia. '+quote});assert.ok(r.alerts.some(a=>a.concept==='consciousness'));assert.ok(!has(r,'consciousness'));}
 for(const quote of ['Lúcido.','Glasgow 15.','Nega alteração de consciência.']){const r=E.analyze({transcript:'Cefaleia. '+quote});assert.equal(r.facts.consciousness.state,'known_absent');assert.ok(!r.alerts.some(a=>a.concept==='consciousness'));}
 const invalid=E.analyze({transcript:'Cefaleia. Glasgow 99.'});assert.equal(invalid.items.find(i=>i.concept==='consciousness').status,'confirm');
});
test('demographics: explicit patient speech informs context without borrowing ages from history or relatives',()=>{
 const r=E.analyze({transcript:'Mulher, 32 anos. Dor abdominal. Cirurgia há 10 anos. Minha mãe tem 70 anos.'});assert.equal(r.demographics.age,32);assert.equal(r.demographics.sex,'feminino');assert.ok(has(r,'pregnancy'));assert.match(r.demographics.evidence.age[0].quote,/32 anos/);
 assert.equal(E.demographics({transcript:'Qual sua idade? Minha mãe tem 70 anos. Cirurgia há 10 anos.'}).age,'');
 assert.equal(E.demographics({transcript:'Paciente de 30 anos. Paciente de 60 anos.'}).age,'');
 assert.equal(E.demographics({transcript:'Paciente de 30 anos. Corrigindo, idade 60 anos.'}).age,60);
 assert.ok(!has(E.analyze({transcript:'Mulher, 70 anos. Dor abdominal.'}),'pregnancy'));
});
test('documented adult extreme vitals are alerts with exact evidence, normal values are not',()=>{
 const text='Paciente de 40 anos. Dor torácica. PA 80/50; FC 140; FR 30; SatO2 85%; temperatura 34,5 °C.';
 const r=E.analyze({transcript:text});for(const id of ['bp','hr','rr','spo2','temperature']){const a=r.alerts.find(a=>a.concept===id);assert.ok(a,id);assert.ok(text.includes(a.evidence[0].quote));}
 const normal=E.analyze({transcript:'Paciente de 40 anos. Dor torácica. PA 120/80; FC 80; FR 16; SatO2 98%; temperatura 36,5 °C.'});assert.equal(normal.alerts.length,0);assert.ok(has(normal,'dyspnea'));
});
test('numeric sentence boundaries preserve vitals before a following question',()=>{const r=E.analyze({transcript:'Paciente de 40 anos. Cefaleia desde hoje. PA 80/50. Médico: Teve rigidez de nuca? Paciente: Não entendi.'});assert.ok(r.alerts.some(a=>a.concept==='bp'));assert.ok(r.confirm.some(i=>i.concept==='meningism'));assert.equal(r.facts.bp.currentEvidence.value,80);assert.equal(E.analyze({transcript:'Paciente de 40 anos. Febre 38.5 °C.'}).facts.temperature.currentEvidence.value,38.5);});
test('vital alerts respect corrections and the documented population instead of applying adult criteria universally',()=>{
 for(const transcript of ['Paciente de 5 anos. Tosse. FC 140.','Tosse. FC 140.','Mulher, 32 anos. Gestante. FC 140.','Paciente de 40 anos. Tosse. Hipercapnia com meta 88 a 92%. SatO2 90%.'])assert.equal(E.analyze({transcript}).alerts.length,0,transcript);
 const r=E.analyze({transcript:'Paciente de 40 anos. Dor torácica. PA 80/50. Corrigindo, PA 120/80.'});assert.ok(!r.alerts.some(a=>a.concept==='bp'));
 const corrected=E.analyze({transcript:'Cefaleia. Glasgow 14. Corrigindo, Glasgow 15.'});assert.ok(!corrected.alerts.some(a=>a.concept==='consciousness'));
});
test('alert links point to actual pending questions and do not resurrect the clarified finding',()=>{
 const r=E.analyze({transcript:'Cefaleia. A dor começou de repente.'}),a=r.alerts.find(a=>a.concept==='sudden');assert.ok(a.related.length);assert.ok(!a.related.includes('sudden'));for(const id of a.related)assert.ok(r.items.some(i=>i.id===id));
});
