import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const loader=read('nexa-hotfix.js');
const layout=read('nexa-layout-static-v18.6.5.js');
const draft=read('nexa-record-draft-history-v18.6.6.js');
const mobile=read('nexa-mobile-shell-v18.6.7.js');
const mobileFlow=read('nexa-mobile-flow-v18.8.1.js');
const exact=read('nexa-auditor-exact-v18.9.js');
const panelQueue=read('nexa-auditor-panel-queue-v18.9.2.js');
const medicalState=read('nexa-medical-layout-state-v18.9.3.js');
const radarStable=read('nexa-radar-stable-state-v18.9.4.js');
const historyNative=read('nexa-history-native-v18.9.5.js');
const auditClear=read('nexa-audit-clear-safety-v18.9.5.js');
const historyStyle=read('nexa-history-style-v18.9.6.js');
const html=read('index.html');
const sw=read('sw.js');
const required=['nexa-hotfix-v1.js','nexa-ui-v3.js','nexa-radar-v4.js','nexa-final-ui-v18.js','nexa-layout-static-v18.6.5.js','nexa-record-draft-history-v18.6.6.js','nexa-mobile-shell-v18.6.7.js','nexa-mobile-flow-v18.8.1.js','nexa-auditor-exact-v18.9.js','nexa-auditor-panel-queue-v18.9.2.js','nexa-medical-layout-state-v18.9.3.js','nexa-radar-stable-state-v18.9.4.js','nexa-history-native-v18.9.5.js','nexa-audit-clear-safety-v18.9.5.js','nexa-history-style-v18.9.6.js'];
for(const mod of required)assert.ok(loader.includes(mod),`loader sem ${mod}`);
for(const forbidden of ['nexa-audit-autosave-v18.5.js','nexa-history-lifecycle-v18.6.9.js','nexa-auditor-functional-v18.9.1.js','nexa-auditor-native-v18.8.js','nexa-auditor-workspace-v18.7.js','nexa-auditor-mobile-fix-v18.7.1.js','nexa-mobile-safe-area-v18.6.8.js','nexa-mobile-top-safe-v18.8.js'])assert.ok(!loader.includes(forbidden),`loader não pode carregar camada antiga/conflitante: ${forbidden}`);
assert.ok(loader.includes('20260906-v1896'));
assert.ok(loader.lastIndexOf('nexa-history-style-v18.9.6.js')>loader.lastIndexOf('nexa-audit-clear-safety-v18.9.5.js'));
for(const id of ['recBtn','consent','timer','processBtn','resetBtn','workspaceHistoryPane','refreshHistoryBtn','updateHistoryBtn','submitAuditBtn','workspaceExamplesPane','useExamples'])assert.ok(html.includes(`id="${id}"`));
assert.ok(html.includes("$('submitAuditBtn').onclick=submitCurrentForAudit"));
assert.ok(html.includes("$('updateHistoryBtn').onclick=saveHistory"));
assert.ok(html.includes("Date.now()-7*24*60*60*1000"));
assert.ok(!layout.includes('MutationObserver')&&!layout.includes('setInterval'));
for(const token of ['__NEXA_RECORD_DRAFT_HISTORY_V18_6_6__',"rec.dataset.nexaStartOnly='1'",'window.nexaRefreshDraftHistory'])assert.ok(draft.includes(token));
for(const token of ['__NEXA_MOBILE_SHELL_V18_6_7__','nexaMobileBottomNav','nexaMobileHeader'])assert.ok(mobile.includes(token));
for(const token of ['__NEXA_MOBILE_FLOW_V18_8_1__','position:sticky!important','document.body.insertBefore(header,app)'])assert.ok(mobileFlow.includes(token));
for(const token of ['__NEXA_AUDITOR_EXACT_V18_9__','Painel de Auditoria','Fila de casos','submit_audit_review'])assert.ok(exact.includes(token));
for(const token of ['__NEXA_AUDITOR_PANEL_QUEUE_V18_9_2__','get_audit_queue','renderPanel','renderQueue'])assert.ok(panelQueue.includes(token));
for(const token of ['__NEXA_MEDICAL_LAYOUT_STATE_V18_9_3__','nexaReturnToMedicalModeStable'])assert.ok(medicalState.includes(token));
for(const token of ['__NEXA_RADAR_STABLE_STATE_V18_9_4__','Perguntas da sessão','Disposição do PS'])assert.ok(radarStable.includes(token));
for(const token of ['__NEXA_HISTORY_NATIVE_V18_9_5__','workspaceHistoryPane','refreshHistoryBtn','Consultas dos últimos 7 dias'])assert.ok(historyNative.includes(token));
for(const token of ['__NEXA_AUDIT_CLEAR_SAFETY_V18_9_5__','updateHistoryBtn','submitAuditBtn','Consulta não foi apagada','nexaFinalizeCaseSafely'])assert.ok(auditClear.includes(token));
for(const token of ['__NEXA_HISTORY_STYLE_V18_9_6__','Consultas dos últimos 7 dias','Meu estilo','style_examples','consultation_history','fallbackSelect','nexaOpenMyStyle196','nexaRefreshHistory196'])assert.ok(historyStyle.includes(token),`History/My Style sem ${token}`);
assert.ok(!historyStyle.includes('MutationObserver')&&!historyStyle.includes('setInterval'),'History/My Style não pode usar loops contínuos');
assert.ok(sw.includes('nexa-v18-9-6-history-style-20260906'));
assert.ok(sw.includes('20260906-v1896'));
assert.ok(sw.includes('cache:"no-store"'));
new Function(loader);new Function(layout);new Function(draft);new Function(mobile);new Function(mobileFlow);new Function(exact);new Function(panelQueue);new Function(medicalState);new Function(radarStable);new Function(historyNative);new Function(auditClear);new Function(historyStyle);new Function(sw);
console.log('NEXA v18.9.6 History + My Style: PASS');
